## To write a terminal command in jupyter, we put a ! mark: !pip install packageName   

In [2]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10) # quick way of generating arrays using numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,10)  # 10 evenly spaced points bw zero and 5 (It is 1Dimensional only)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(3)  # creates identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#To create random arrays np.random.

In [14]:
np.random.rand(5) # returns no of uniform distribution from 0 to 1

array([0.23228442, 0.33843108, 0.42787385, 0.15062826, 0.16218307])

In [15]:
np.random.rand(5,5)  

array([[0.92463271, 0.9481364 , 0.6310199 , 0.67069443, 0.39086495],
       [0.12148974, 0.59123345, 0.18230042, 0.48750333, 0.40130673],
       [0.00830217, 0.91357924, 0.93767126, 0.74398532, 0.50480817],
       [0.73764189, 0.62499598, 0.92013282, 0.49905   , 0.6733857 ],
       [0.51065754, 0.81160777, 0.30397998, 0.85733848, 0.53877659]])

In [23]:
np.random.randn(2) # returns standard normal distribution center around zero

array([-0.52041115, -0.40825874])

In [24]:
np.random.randn(3,3) # 2D matrix

array([[-0.02914279,  0.16038798, -0.22259161],
       [ 0.21715435, -0.25724587, -0.31726393],
       [-0.48099625, -2.39723592,  0.64439831]])

In [29]:
np.random.randint(40,50)  # generates a random integer between 40 and 50, lower is inclusive but higher end is not

43

In [31]:
arr = np.random.randint(1,100,10) # 10 random integers bw 1 and 100

In [32]:
    arr

array([84, 81, 91, 52,  4, 63, 38, 28, 36, 27])

In [33]:
arr.max()  # returns the max no in the array, same we can do for min()

91

In [34]:
arr.argmax()  # returns index of max no in the array

2

In [42]:
arr.reshape(2,5)

array([[84, 81, 91, 52,  4],
       [63, 38, 28, 36, 27]])

In [43]:
arr.shape

(10,)

In [44]:
arr.dtype  #returns the datatype of the integer

dtype('int32')

In [49]:
arr = np.arange(10)

In [50]:
arr[1:5]

array([1, 2, 3, 4])

In [51]:
slice_of_arr = arr[0:6] # making changes in slice_of_arr will affect arr too as numpy dont explicitely creates copies

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:] = 99 # every no of slice_of_arr became 99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr  #as well as for arr too

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [56]:
arr_copy = arr.copy() #to create a copy, now changes in arr_copy won't affect arr

In [57]:
arr_copy[:] = 100

In [58]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr  # arr didnt changed to 100

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [62]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]]) 

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[2][1]

40

In [66]:
arr_2d[2,1]  # Accessing using single bracket comma is used. Less prone to errors hence recommended.

40

In [67]:
arr_2d[:2, 1:]  # Grab everything upto row 2, and grab everything from column 1 all the way to the end

array([[10, 15],
       [25, 30]])

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [70]:
arr = np.arange(1, 11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
bool_arr = arr>6

In [73]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [74]:
arr[bool_arr]  # returns those for which bool_arr was true

array([ 7,  8,  9, 10])

In [76]:
arr[arr>6]  # we will use this

array([ 7,  8,  9, 10])

In [77]:
arr[arr<3]

array([1, 2])